//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNCOperation
    {
        public CNCOperation()
        {
            this.Detailings = new HashSet<Detailing>();
        }
    
        public int CNCOperationID { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<int> InputQuantityCNC { get; set; }
        public Nullable<int> OutputQuantityCNC { get; set; }
        public Nullable<int> DMRCNC { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Description { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<Detailing> Detailings { get; set; }
    }
}
