//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailing
    {
        public Detailing()
        {
            this.QualityControls = new HashSet<QualityControl>();
        }
    
        public int DetailingID { get; set; }
        public Nullable<int> CNCOperationID { get; set; }
        public Nullable<int> InputQuantityDetail { get; set; }
        public Nullable<int> OutputQuantityDetail { get; set; }
        public Nullable<int> DMRDetail { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual CNCOperation CNCOperation { get; set; }
        public virtual ICollection<QualityControl> QualityControls { get; set; }
    }
}
