//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FPYEntities : DbContext
    {
        public FPYEntities()
            : base("name=FPYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CNCOperation> CNCOperations { get; set; }
        public DbSet<Detailing> Detailings { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<QualityControl> QualityControls { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<WorkOrder> WorkOrders { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
