//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPY
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControl
    {
        public int QCOperationID { get; set; }
        public Nullable<int> DetailingID { get; set; }
        public Nullable<int> InputQuantityQC { get; set; }
        public Nullable<int> OutputQuantityQC { get; set; }
        public Nullable<int> DMRQC { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Detailing Detailing { get; set; }
    }
}
