//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPY
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.CNCOperations = new HashSet<CNCOperation>();
        }
    
        public int WorkOrderID { get; set; }
        public Nullable<int> PartNo { get; set; }
        public string WorkOrderNo { get; set; }
        public Nullable<int> OutputQuantityPC { get; set; }
        public string Description { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual ICollection<CNCOperation> CNCOperations { get; set; }
        public virtual Product Product { get; set; }
    }
}
